"""
Risk scoring, alerts, alert policies, tickets, relationships, and audit models

Provides the operational layer for the EASM platform: risk score snapshots,
alerting with configurable policies, asset-to-asset relationship graphs,
external ticket tracking, and a compliance audit trail.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    ForeignKey,
    Text,
    Enum,
    Float,
    Boolean,
    Index,
    JSON,
)
from sqlalchemy.orm import relationship

from app.models.database import Base


class RiskScore(Base):
    """
    Point-in-time risk score snapshot.

    Captures the computed risk score for a given scope (issue, asset, or
    organization) after each scan run, with a breakdown of contributing
    factors and the delta from the previous score.
    """

    __tablename__ = "risk_scores"

    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)
    scope_type = Column(String(20), nullable=False)  # 'issue', 'asset', 'organization'
    scope_id = Column(Integer)  # issue_id, asset_id, or null for org
    scan_run_id = Column(Integer, ForeignKey("scan_runs.id", ondelete="SET NULL"))
    score = Column(Float, nullable=False)  # 0-100
    grade = Column(String(2))  # A, B, C, D, F
    components = Column(JSON)  # Score breakdown {base_severity, confidence, exposure_factor, ...}
    explanation = Column(JSON)  # {top_drivers: [{description, contribution}, ...]}
    previous_score = Column(Float)
    delta = Column(Float)
    scored_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index("idx_rs_tenant", "tenant_id"),
        Index("idx_rs_scope", "scope_type", "scope_id"),
        Index("idx_rs_scan_run", "scan_run_id"),
        Index("idx_rs_scored_at", "scored_at"),
    )

    def __repr__(self):
        return f"<RiskScore(id={self.id}, scope={self.scope_type}:{self.scope_id}, score={self.score})>"


class AlertStatus(enum.Enum):
    PENDING = "pending"
    SENT = "sent"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class Alert(Base):
    """
    Alert generated by the platform when a policy condition is met.

    Alerts are linked to an optional policy, an event type, and the
    related asset/finding that triggered them.
    """

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)
    policy_id = Column(Integer, ForeignKey("alert_policies.id"))
    event_type = Column(String(50), nullable=False)  # 'finding_new', 'asset_new', 'cert_expiring', 'score_changed'
    severity = Column(String(20), nullable=False)
    title = Column(String(500), nullable=False)
    body = Column(Text)
    related_asset_id = Column(Integer, ForeignKey("assets.id", ondelete="SET NULL"))
    related_finding_id = Column(Integer, ForeignKey("findings.id", ondelete="SET NULL"))
    status = Column(Enum(AlertStatus), default=AlertStatus.PENDING)
    channels_sent = Column(JSON)  # ["slack", "email"]
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    sent_at = Column(DateTime)
    acknowledged_at = Column(DateTime)

    __table_args__ = (
        Index("idx_alert_tenant", "tenant_id"),
        Index("idx_alert_status", "status"),
        Index("idx_alert_severity", "severity"),
        Index("idx_alert_created", "created_at"),
        Index("idx_alert_policy", "policy_id"),
    )

    def __repr__(self):
        return f"<Alert(id={self.id}, event='{self.event_type}', severity='{self.severity}')>"


class AlertPolicy(Base):
    """
    Configurable alert policy defining when and how alerts are dispatched.

    Supports event type filtering, condition matching, multi-channel
    delivery, cooldown windows, and digest mode for batching.
    """

    __tablename__ = "alert_policies"

    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)
    name = Column(String(255), nullable=False)
    event_types = Column(JSON, nullable=False)  # ["finding_new", "asset_new"]
    conditions = Column(JSON)  # {"severity": "critical", "control_id": "TKO-*"}
    channels = Column(JSON, nullable=False)  # [{"type": "slack", "webhook_url": "..."}, {"type": "email", "to": "..."}]
    cooldown_minutes = Column(Integer, default=1440)  # Default 24h
    digest_mode = Column(Boolean, default=False)
    enabled = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(
        DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc)
    )

    __table_args__ = (
        Index("idx_ap_tenant", "tenant_id"),
        Index("idx_ap_enabled", "tenant_id", "enabled"),
    )

    def __repr__(self):
        return f"<AlertPolicy(id={self.id}, name='{self.name}', enabled={self.enabled})>"


class Relationship(Base):
    """
    Asset-to-asset relationship for graph building.

    Represents directed edges in the attack surface graph, e.g.
    DNS resolution, CNAME chains, redirects, certificate coverage,
    and parent-domain hierarchies.
    """

    __tablename__ = "relationships"

    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)
    source_asset_id = Column(Integer, ForeignKey("assets.id", ondelete="CASCADE"), nullable=False)
    target_asset_id = Column(Integer, ForeignKey("assets.id", ondelete="CASCADE"), nullable=False)
    rel_type = Column(
        String(50), nullable=False
    )  # 'resolves_to', 'cname_to', 'ns_for', 'mx_for', 'redirects_to', 'cert_covers', 'hosts', 'parent_domain'
    rel_metadata = Column("metadata", JSON)
    first_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    last_seen_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index("idx_rel_tenant", "tenant_id"),
        Index("idx_rel_source", "source_asset_id"),
        Index("idx_rel_target", "target_asset_id"),
        Index("idx_rel_type", "rel_type"),
        Index("idx_rel_unique", "source_asset_id", "target_asset_id", "rel_type", unique=True),
    )

    def __repr__(self):
        return f"<Relationship(id={self.id}, {self.source_asset_id} --{self.rel_type}--> {self.target_asset_id})>"


class AuditLog(Base):
    """
    Compliance audit trail.

    Records every significant user or system action for regulatory
    compliance, forensic investigation, and operational monitoring.
    """

    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"))
    action = Column(String(100), nullable=False)  # 'create', 'update', 'delete', 'login', 'status_change'
    entity_type = Column(String(50))  # 'issue', 'finding', 'asset', 'alert_policy', etc.
    entity_id = Column(Integer)
    old_value = Column(JSON)
    new_value = Column(JSON)
    ip_address = Column(String(45))  # IPv4 or IPv6
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        Index("idx_audit_tenant", "tenant_id"),
        Index("idx_audit_user", "user_id"),
        Index("idx_audit_entity", "entity_type", "entity_id"),
        Index("idx_audit_created", "created_at"),
        Index("idx_audit_action", "action"),
    )

    def __repr__(self):
        return f"<AuditLog(id={self.id}, action='{self.action}', entity={self.entity_type}:{self.entity_id})>"
